import os, sys

env = Environment()

env.Append(CPPPATH = [os.path.join(os.environ['FABRIC_DIR'], 'include')])
env.Append(LIBPATH = [os.path.join(os.environ['FABRIC_DIR'], 'lib')])
env.Append(CPPDEFINES = ['FEC_SHARED', 'FECS_SHARED'])

# Fabric Engine libraries
env.Append(LIBS = ['FabricSplice-2.0_s', 'FabricCore-2.0'])

# standard libraries
if sys.platform == 'win32':
  env.Append(LIBS = ['user32', 'advapi32', 'gdi32', 'shell32', 'ws2_32', 'Opengl32', 'glu32'])
else:
  env.Append(LIBS = ['X11', 'GLU', 'GL', 'dl', 'pthread'])

p = env.Program('rtvals', Glob('*.cpp'))
