import os, sys

env = Environment(MSVC_VERSION='12.0')

env.Append(CPPPATH = [os.path.join(os.environ['FABRIC_DIR'], 'include')])
env.Append(LIBPATH = [os.path.join(os.environ['FABRIC_DIR'], 'lib')])
env.Append(CPPDEFINES = ['FEC_SHARED', 'FECS_STATIC'])

# Fabric Engine libraries
env.Append(LIBS = ['FabricSplice-2.4_s', 'FabricCore-2.4'])

# standard libraries
if sys.platform == 'win32':
  env.Append(LIBS = ['user32', 'advapi32', 'gdi32', 'shell32', 'ws2_32', 'Opengl32', 'glu32'])
else:
  env.Append(LIBS = ['X11', 'GLU', 'GL', 'dl', 'pthread'])

p = env.Program('logging', Glob('*.cpp'))
