import os, sys

env = Environment()

env.Append(CPPPATH = [os.environ['FABRICSPLICE_API_DIR']])
env.Append(LIBPATH = [os.environ['FABRICSPLICE_API_DIR']])
env.Append(CPPDEFINES = ['FEC_STATIC', 'FECS_STATIC'])

# Fabric Engine libraries
env.Append(LIBS = ['FabricSplice-1.11.1_ss', 'FabricCore-1.11_s'])

# standard libraries
if sys.platform == 'win32':
  env.Append(LIBS = ['user32', 'advapi32', 'gdi32', 'shell32', 'ws2_32', 'Opengl32', 'glu32'])
else:
  env.Append(LIBS = ['X11', 'GLU', 'GL', 'dl', 'pthread'])

p = env.Program('persistence', Glob('*.cpp'))
